# Generated by Django 6.0.6 on 2026-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=32),
        ),
    ]
